
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import DA.CreateFoodDA;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class NewJFrame extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    ResultSet rs;
    String msg = "";
    CreateFoodDA cfda = new CreateFoodDA();
    
    public NewJFrame() {
        initComponents();
        CreateFoodDA cfda = new CreateFoodDA();
        ResultSet rs = cfda.generateFoodID("1001");
        int newfoodid = 1001;
        try{
        while(rs.next()){
            newfoodid++;
        }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        String foodid = newfoodid + "";
        jtfItemID.setText(foodid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblItemID = new javax.swing.JLabel();
        jlblItemImage = new javax.swing.JLabel();
        jlblItemName = new javax.swing.JLabel();
        jlblDescription = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JLabel();
        jtfItemID = new javax.swing.JTextField();
        jtfItemName = new javax.swing.JTextField();
        jtfDesc = new javax.swing.JTextField();
        jtfPrice = new javax.swing.JTextField();
        jlblRestID = new javax.swing.JLabel();
        jtfRestID = new javax.swing.JTextField();
        jbtClear = new javax.swing.JButton();
        jbtCreate = new javax.swing.JButton();
        jbtExit = new javax.swing.JButton();
        jtfItemImage = new javax.swing.JTextField();
        jbtBrowse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblItemID.setText("            Item ID");

        jlblItemImage.setText("          Item Image");

        jlblItemName.setText("          Item Name");

        jlblDescription.setText("           Description");

        jlblPrice.setText("               Price");

        jtfItemID.setEditable(false);
        jtfItemID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfItemID.setEnabled(false);

        jtfItemName.setToolTipText("");

        jlblRestID.setText("    Restaurant ID");

        jbtClear.setText("CLEAR");
        jbtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearActionPerformed(evt);
            }
        });

        jbtCreate.setBackground(new java.awt.Color(51, 255, 0));
        jbtCreate.setText("CREATE");
        jbtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCreateActionPerformed(evt);
            }
        });

        jbtExit.setText("EXIT");
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });

        jbtBrowse.setText("Browse");
        jbtBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblRestID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfRestID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblItemImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfItemImage))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDesc))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPrice))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCreate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfItemID, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(jlblItemID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlblItemImage, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(jtfItemImage)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbtCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(jbtClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfDesc)
                            .addComponent(jlblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfRestID, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jlblRestID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCreateActionPerformed

        if(jtfItemImage.getText().equals("") || jtfItemName.getText().equals("") || jtfDesc.getText().equals("") || jtfPrice.getText().equals("") || jtfRestID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please complete the form.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            boolean check = true;
            boolean existofdecimalpoint = false;
            for(int i = 0;i < jtfPrice.getText().length();i++){
                if(!(Character.isDigit(jtfPrice.getText().charAt(i))) && jtfPrice.getText().charAt(i) == '.' && existofdecimalpoint == true){
                    check = false;
                }else if(!(Character.isDigit(jtfPrice.getText().charAt(i))) && jtfPrice.getText().charAt(i) == '.' && existofdecimalpoint == false){
                    existofdecimalpoint = true;
                }else if(!(Character.isDigit(jtfPrice.getText().charAt(i))) && !(jtfPrice.getText().charAt(i) == '.')){
                    check = false;
                }
            }
            if(check == false){
                JOptionPane.showMessageDialog(null, "Incorrect format of price entered.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else{
                double price = Double.parseDouble(jtfPrice.getText());
                try{
                    cfda.addRecord(jtfItemID.getText(), jtfItemImage.getText(), jtfItemName.getText(), jtfDesc.getText(), price, jtfRestID.getText());
                    JOptionPane.showMessageDialog(null, "Food Added.", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    CreateFoodDA cfda = new CreateFoodDA();
                    ResultSet rs = cfda.generateFoodID("1001");
                    int newfoodid = 1001;
                    try{
                        while(rs.next()){
                            newfoodid++;
                        }
                    }catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
        
                    String foodid = newfoodid + "";
                    jtfItemID.setText(foodid);
                    jtfItemImage.setText("");
                    jtfItemName.setText("");
                    jtfDesc.setText("");
                    jtfPrice.setText("");
                }catch (SQLException ex){
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_jbtCreateActionPerformed

    private void jbtBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrowseActionPerformed
               JFileChooser chooser = new JFileChooser();
       chooser.setCurrentDirectory(new java.io.File("."));
       chooser.setDialogTitle("Choose Folder");
       chooser.setAcceptAllFileFilterUsed(false);
       
       if(chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
           File path = chooser.getSelectedFile();
           jtfItemImage.setText(path.toString());
       }else{
           JOptionPane.showMessageDialog(null, "No path selected.", "ERROR", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jbtBrowseActionPerformed

    private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
        jtfItemImage.setText("");
        jtfItemName.setText("");
        jtfDesc.setText("");
        jtfPrice.setText("");
    }//GEN-LAST:event_jbtClearActionPerformed

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        dispose();
    }//GEN-LAST:event_jbtExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtBrowse;
    private javax.swing.JButton jbtClear;
    private javax.swing.JButton jbtCreate;
    private javax.swing.JButton jbtExit;
    private javax.swing.JLabel jlblDescription;
    private javax.swing.JLabel jlblItemID;
    private javax.swing.JLabel jlblItemImage;
    private javax.swing.JLabel jlblItemName;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblRestID;
    private javax.swing.JTextField jtfDesc;
    private javax.swing.JTextField jtfItemID;
    private javax.swing.JTextField jtfItemImage;
    private javax.swing.JTextField jtfItemName;
    private javax.swing.JTextField jtfPrice;
    private javax.swing.JTextField jtfRestID;
    // End of variables declaration//GEN-END:variables
}
